version: "3.8"

services:
  web:
    build: .
    image: shyft-main:latest
    container_name: shyft-main
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./public:/app/public:ro
